version: "3.8"

name: mssql
services:
  server:
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=MyStrongPass123
    ports:
      - 1433:1433
    image: mcr.microsoft.com/mssql/server:2022-latest
